import * as fs from 'fs';
import * as path from 'path';

import { joinAppUrl, RETELL_WEBHOOK_PATH } from './routes';
import { RECEPTIONIST_FUNCTION_SPECS } from './retellFunctionSpecs';
import { getPlumberRetellGeneralPrompt, PLUMBER_RETELL_BEGIN_MESSAGE } from './plumberPrompt';

export type WriteGeneratedDocsOptions = {
  /** Placeholder shown in markdown, e.g. \`https://your-public-host.example.com\` */
  appBasePlaceholder: string;
};

export function buildRetellFunctionsMarkdown(opts: WriteGeneratedDocsOptions): string {
  const base = opts.appBasePlaceholder.replace(/\/+$/, '');
  const lines: string[] = [];
  lines.push('# Retell custom functions (generated)');
  lines.push('');
  lines.push(
    'This file is regenerated by `npm run retell:setup` (or `writeGeneratedDocs`). URLs use your public `APP_BASE_URL`.',
  );
  lines.push('');
  lines.push('## Authentication');
  lines.push('');
  lines.push('All endpoints require **one** of:');
  lines.push('');
  lines.push('- `Authorization: Bearer <RETELL_TOOL_SHARED_SECRET>`');
  lines.push('- `x-retell-tool-secret: <RETELL_TOOL_SHARED_SECRET>`');
  lines.push('');
  lines.push('## Webhook (separate from tools)');
  lines.push('');
  lines.push(`- **POST** \`${base}${RETELL_WEBHOOK_PATH}\` — Retell server-to-server events (signed with \`x-retell-signature\`).`);
  lines.push('');

  for (const spec of RECEPTIONIST_FUNCTION_SPECS) {
    const url = joinAppUrl(base, `/api/receptionist/providers/retell/functions/${spec.slug}`);
    lines.push(`## ${spec.slug}`);
    lines.push('');
    lines.push(`- **Purpose:** ${spec.purpose}`);
    lines.push(`- **When to call:** ${spec.whenToCall}`);
    lines.push(`- **HTTP:** \`POST ${url}\``);
    lines.push('');
    lines.push('### Request JSON schema (illustrative)');
    lines.push('');
    lines.push('```json');
    lines.push(JSON.stringify(spec.requestSchema, null, 2));
    lines.push('```');
    lines.push('');
    lines.push('### Response JSON schema (success envelope)');
    lines.push('');
    lines.push('```json');
    lines.push(JSON.stringify(spec.responseSchema, null, 2));
    lines.push('```');
    lines.push('');
    lines.push('### Example request');
    lines.push('');
    lines.push('```json');
    lines.push(JSON.stringify(spec.example.request, null, 2));
    lines.push('```');
    lines.push('');
    lines.push('### Example success response');
    lines.push('');
    lines.push('```json');
    lines.push(JSON.stringify(spec.example.response, null, 2));
    lines.push('```');
    lines.push('');
  }

  lines.push('## Errors');
  lines.push('');
  lines.push('Failed tool calls return JSON such as `{ "ok": false, "error": { "code": "...", "message": "..." } }` with 4xx status.');
  lines.push('');
  return lines.join('\n');
}

export function buildRetellFunctionsJson(opts: WriteGeneratedDocsOptions): unknown {
  const base = opts.appBasePlaceholder.replace(/\/+$/, '');
  return {
    generated: true,
    app_base_url_placeholder: base,
    auth: {
      headers: [
        'Authorization: Bearer <RETELL_TOOL_SHARED_SECRET>',
        'x-retell-tool-secret: <RETELL_TOOL_SHARED_SECRET>',
      ],
    },
    webhook: {
      method: 'POST',
      url: joinAppUrl(base, RETELL_WEBHOOK_PATH),
    },
    functions: RECEPTIONIST_FUNCTION_SPECS.map((spec) => ({
      name: spec.slug,
      purpose: spec.purpose,
      when_to_call: spec.whenToCall,
      method: 'POST',
      url: joinAppUrl(base, `/api/receptionist/providers/retell/functions/${spec.slug}`),
      request_schema: spec.requestSchema,
      response_schema: spec.responseSchema,
      example: spec.example,
    })),
  };
}

export function buildRetellAgentScriptGeneratedMarkdown(): string {
  const body = getPlumberRetellGeneralPrompt();
  return [
    '# PlumberOS — Retell agent script (generated)',
    '',
    '> Generated from `src/lib/receptionist/retell-setup/plumberPrompt.ts`. Run `npm run retell:setup` to refresh.',
    '',
    '## Begin message (Retell LLM `begin_message`)',
    '',
    '```text',
    PLUMBER_RETELL_BEGIN_MESSAGE,
    '```',
    '',
    '## General prompt (`general_prompt`)',
    '',
    body
      .split('\n')
      .map((line) => (line.trim() === '' ? '' : line))
      .join('\n'),
    '',
  ].join('\n');
}

export function writeGeneratedDocs(repoRoot: string, opts: WriteGeneratedDocsOptions): void {
  const docsDir = path.join(repoRoot, 'docs', 'receptionist');
  fs.mkdirSync(docsDir, { recursive: true });

  const mdPath = path.join(docsDir, 'retell-functions.generated.md');
  const jsonPath = path.join(docsDir, 'retell-functions.generated.json');
  const agentPath = path.join(docsDir, 'retell-agent-script.generated.md');

  fs.writeFileSync(mdPath, buildRetellFunctionsMarkdown(opts), 'utf8');
  fs.writeFileSync(jsonPath, `${JSON.stringify(buildRetellFunctionsJson(opts), null, 2)}\n`, 'utf8');
  fs.writeFileSync(agentPath, buildRetellAgentScriptGeneratedMarkdown(), 'utf8');
}
